### ISSUE TITLE
Const values in package schema are not set, e.g.: create Kubernetes resources without "kind", "apiVersion"

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#153]
Acceptance criteria: the following YAML example should create a Kubernetes namespace as-is. 

In most of our languages, the equivalent to this YAML should create an automatically named namespace resource:

```yaml
resources:
  namespace:
    type: kubernetes:core/v1:Namespace
```

Equivalent to `new k8s.core.v1.Namespace('namespace')` in TypeScript.

However this causes an error when creating the resource with an error that the property "kind" is an empty string.

That comes from the package schema for a namespace, copied below, defining two "const" properties:

```yaml
        "kubernetes:core/v1:Namespace": {
            "description": "Namespace provides a scope for Names. Use of multiple namespaces is optional.",
            "properties": {
                "apiVersion": {
                    "type": "string",
                    "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
                    "const": "v1"
                },
                "kind": {
                    "type": "string",
                    "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
                    "const": "Namespace"
                },
...
```

These constants do not appear in the API docs, as the generated SDKs for each language will set these constants for the user. (This raises another question we will merely note, as answering it is out of scope for YAML: why are they properties and not built in to the provider binary if users cannot provide them and they are hardcoded to a specific value?)

This affects all resources which define constants, and a quick scan of "const" declarations in schema.json found ~3400 entries. None at an indentation level greater than a top-level property key, though I used grep and not a json parser to see if any nested objects define a constant. I would be surprised if our codegen supported nested consts, so I'm assuming not and that we can solve this by addressing the top-level resource properties in YAML.
