### ISSUE TITLE
Eject modifies resource IDs as well as declaration names

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#160]
Declaring a resource like so in YAML:

```yaml
resources:
  demo-ns: # namespace name generated based on resource name
    type: kubernetes:core/v1:Namespace
    options:
      provider: ${k8sProvider}
```   

Is ejected as:

TypeScript:
```ts
const demons = new kubernetes.core.v1.Namespace("demons", {}, {
    provider: k8sProvider,
});
```

Python:
```py
demons = kubernetes.core.v1.Namespace("demons", opts=pulumi.ResourceOptions(provider=k8s_provider))
```

The resource ID being de-hyphen-cased results in a program that will delete and create a new resource.
