### ISSUE TITLE
awsx program fails to convert to Go

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#185]
The following YAML program:

```yaml
name: awsx
runtime: yaml
resources:
  cluster:
    type: aws:ecs:Cluster
  lb:
    type: awsx:lb:ApplicationLoadBalancer
  nginx:
    type: awsx:ecs:FargateService
    properties:
      cluster: ${cluster.arn}
      taskDefinitionArgs:
        container:
          image: nginx:latest
          cpu: 512
          memory: 128
          portMappings:
            - containerPort: 80
              targetGroup: ${lb.defaultTargetGroup}
outputs:
  url: ${lb.loadBalancer.dnsName}
```

Fails to `pulumi convert` first because of the output `url`. The error is error: could not load yaml program: failed to load YAML program: **internal error: program.pp:22,25-33: cannot traverse value of type none;**, with the bold part shown by modifying the `Errorf` to print `err`.

https://github.com/pulumi/pulumi-yaml/blob/d3413894bdd802c063fb2d76d8fcbfb641adc2bb/pkg/pulumiyaml/codegen/eject.go#L54-L56

After removing the outputs, the emitted Go is still invalid. I've uploaded a copy of it converted here: https://github.com/pulumi/pulumi-yaml/blob/dc13e16f4066ebf62c745fb86755e61aad0c61ea/examples/awsx/go/main.go#L1-L41

 There are a few issues:

1. Package `github.com/pulumi/pulumi-awsx/sdk/go/awsx/lb` is imported and the `lb` resource declaration shadows the package name.
1. There are two `ecs` packages imported which shadow one another.
1. The `TargetGroup` is plain, we're passing it an output

**Comment by AaronFriel** [comment]
Adding to this, I think that name shadowing issues aside (need to create a separate issue), the main issue I want to solve right now is that the final output doesn't generate. The shallow plain values are fixed in #195.

Right now the issue is:

```
resources:
  lb:
    type: awsx:lb:ApplicationLoadBalancer
outputs:
  url: ${lb.loadBalancer.dnsName}
```

We want to generate Go like the following:

```go
ctx.Export("dnsName", lb.LoadBalancer.DnsName())
```

But right now we hit an error:

```
error: could not load yaml program: failed to load YAML program: internal error: program.pp:26,25-33: cannot traverse value of type none;
```

It looks like we're not understanding in codegen what that "resource output" type is in the accessor parts.
