### ISSUE TITLE
Resource in awsx provider expects plain value, errors due to receiving Output

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#193]
Using the same YAML program as in #184, an error occurs on preview due to the `taskDefinitionArgs` property being an Output, when it should be plain with sub-sub-properties allowed to be Outputs. 

See this related bug and change in the Go SDK codegen to allow shallow plain values: 
- https://github.com/pulumi/pulumi/issues/9507

Program and output:

```
name: awsx
runtime: yaml
resources:
  cluster:
    type: aws:ecs:Cluster
  lb:
    type: awsx:lb:ApplicationLoadBalancer
  nginx:
    type: awsx:ecs:FargateService
    properties:
      cluster: ${cluster.arn}
      taskDefinitionArgs:
        container:
          image: nginx:latest
          cpu: 512
          memory: 128
          portMappings:
            - containerPort: 80
              targetGroup: ${lb.defaultTargetGroup}
outputs: omitted here, separate bug
  url: ${lb.loadBalancer.dnsName}
```

```
pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/friel/awsx/dev/previews/84427b80-1851-4647-9030-bd8d2b674602

     Type                                  Name      Plan       Info
 +   pulumi:pulumi:Stack                   awsx-dev  create     1 error; 11 messages
 +   ├─ aws:ecs:Cluster                    cluster   create     
 +   ├─ awsx:lb:ApplicationLoadBalancer    lb        create     
 +   │  ├─ aws:ec2:SecurityGroup           lb        create     
 +   │  ├─ aws:lb:TargetGroup              lb        create     
 +   │  ├─ aws:lb:LoadBalancer             lb        create     
 +   │  └─ aws:lb:Listener                 lb-0      create     
 +   └─ awsx:ecs:FargateService            nginx     create     
 +      └─ awsx:ecs:FargateTaskDefinition  nginx     create     
 
Diagnostics:
  pulumi:pulumi:Stack (awsx-dev):
    Error: Exactly one of [container] or [containers] must be provided: Error: Exactly one of [container] or [containers] must be provided
        at normalizeFargateTaskDefinitionContainers (/home/friel/.pulumi/plugins/ecs/fargateTaskDefinition.ts:120:15)
        at new FargateTaskDefinition (/home/friel/.pulumi/plugins/ecs/fargateTaskDefinition.ts:60:28)
        at new FargateService (/home/friel/.pulumi/plugins/ecs/fargateService.ts:55:30)
        at awsx:ecs:FargateService (/home/friel/.pulumi/plugins/resources.ts:26:45)
        at construct (/home/friel/.pulumi/plugins/resources.ts:56:12)
        at Provider.construct (/home/friel/.pulumi/plugins/index.ts:43:35)
        at Server.<anonymous> (/home/friel/.pulumi/plugins/resource-awsx-v1.0.0/node_modules/@pulumi/provider/server.ts:322:48)
        at Generator.next (<anonymous>)
        at fulfilled (/home/friel/.pulumi/plugins/resource-awsx-v1.0.0/node_modules/@pulumi/pulumi/provider/server.js:18:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
