### ISSUE TITLE
Improve error message when user forgets "properties"?

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-yaml#197]
Is it possible to improve the error message if someone places a YAML attribute that should be under properties? (This idea occurred to me because the error message for specifying an invalid property name is so helpful and the onboarding was so gentle for me and because I made this mistake several times while writing my first Pulumi YAML programs.)

e.g.:

```yaml
myBucket:
  type: aws:s3:bucket
  bucket: 'my-bucket-name'
```

Could result in some error message like:

```
Resource 'myBucket' has invalid key 'bucket'. Did you mean to put this key for the resource under 'properties', e.g.:

myBucket:
  # ...
  properties:
    bucket: 'my-bucket-name'
```
