### ISSUE TITLE
YAML function to read a file and manipulate its contents

### ISSUE THREAD

**Issue by mchaynes** [pulumi/pulumi-yaml#200]
### What happened?

I am attempting to read in a file in a pulumi yaml program. I want to set an `output` property to the contents of a file. However, I'm seeing a JSON object representing the file asset instead of the **contents** of the file

### Steps to reproduce

Create the following files:
`./README.md`
```
# Example Readme
Readme
```

`./Pulumi.yml`
```yaml
name: readme
runtime: yaml
description: example
outputs:
  # Export the name of the bucket
  bucketName: ${bucket.id}
  readme:
    Fn::FileAsset: ./README.md
```

Run `pulumi up`

### Expected Behavior

The output should be set to the _contents_ of the FileAsset, not a JSON object.

### Actual Behavior

<img width="1244" alt="Screenshot 2022-05-12 at 10 14 09@2x" src="https://user-images.githubusercontent.com/17183569/168140402-f0305112-58fb-4e43-9248-089faa00ac2c.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
