### ISSUE TITLE
Missing values report missing Resources

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#206]
### What happened?

Confusing error message for missing variable.

### Steps to reproduce

Run pulumi up on the following template:
```yaml
resources:
  myBucket:
    type: aws:s3:Bucket
    properties:
      bucket: ${other}

name: yaml-example
runtime: yaml
description: A minimal Pulumi YAML program
```

### Expected Behavior

```
    Error: resource/variable/configuration value "other" not found
      on Pulumi.yaml line 5:
       5:       bucket: ${other}
    resource/variable/configuration value "other" not found
```

Or something similar.

### Actual Behavior

    Error: resource "other" not found
      on Pulumi.yaml line 5:
       5:       bucket: ${other}
    resource "other" not found
 

### Versions used

3.28.0-alpha.1652812404+65139da6.dirty

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
