### ISSUE TITLE
reserve `Fn::` prefix for keys

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-yaml#222]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
If a user is running a `Pulumi.yaml` that uses newly supported intrinsics on an older runtime, unexpected behavior will likely occur.
```yaml
variables:
  kubeconfigs:
    Fn::Invoke:
      Function: azure-native:containerservice:listManagedClusterUserCredentials
      Arguments:
        resourceGroupName: ${rg.name}
        resourceName: ${cluster-1.name}
  kubeconfigb64:
    Fn::FromBase64: ${kubeconfigs.kubeconfigs[0].value}
...
outputs:
  kconfig: ${kubeconfigb64}
```

`Fn::FromBase64` is unimplemented yet so on the current runtime this would output:
```
  + kconfig: {
      + Fn::FromBase64: "YXBpVmVyc2...
```
instead of
```
  + kconfig: "YXBpVmVyc2...
```
