### ISSUE TITLE
Abbreviated property setters

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [pulumi/pulumi-yaml#223]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
It would be great if multiple levels could be avoided by doing something like this:
```
managedCluster:
    type: azure-native:containerservice:ManagedCluster
    properties:
      addonProfiles.omsagent.config:
        logAnalyticsWorkspaceResourceID: ${workspace.id}
```
Instead of something like this:
```
managedCluster:
    type: azure-native:containerservice:ManagedCluster
    properties:
      addonProfiles:
        omsagent:
          config:
            logAnalyticsWorkspaceResourceID: ${workspace.id}
```
I don't see how this could be done with the other languages, but I am thinking that this might be possible with yaml.
