### ISSUE TITLE
Avoid need for explicit configuration

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [pulumi/pulumi-yaml#224]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
To put the github_token secret in my stack config like this:
```
config:
  github-actions-runners-cluster:github_token:
    secure: AAABAFldjy/W2WKfQv1Q7...
```
I needed to add this configuration:
```
configuration:
  github_token:
    type: String
```
Which makes my Pulumi yaml program 3 lines longer without adding anything.

**Comment by AaronFriel** [comment]
This was implemented by @aq17 and @iwahbe in the move to supporting project level configuration. Because YAML now receives config keys from the engine, the following trivial program works:

```yaml
name: output-foo
runtime: yaml
outputs:
    name: ${foo}
```

With the following config file:

```yaml
# Pulumi.dev.yaml
config:
  foo: bar
```

With this program, `pulumi preview` correctly displays:

```
Outputs:
    name: "bar"
```
