### ISSUE TITLE
Add fn::Replace function

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [pulumi/pulumi-yaml#225]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Since some Azure resources does not allow special characters (Storage, Key Vault), removing dashes or similar characters from names would make it much easier to keep names in variables.

```
  rgName: eu-github-actions-runners-t
  sanitizedName: # Should become 'eugithubactionsrunnerst'
    Fn::Replace:
      - ${name}
      - '-'
      - ''
  storageName: ${sanitizedName}-st
```
Or 
```
  rgName: eu-github-actions-runners-t
  storageName: # Should become 'eugithubactionsrunnerstst'
    Fn::Replace:
      - ${name}-st
      - '-'
      - ''
```

**Comment by AaronFriel** [comment]
Would a "case" or "slug" function suit you better? Replace is very generic, can produce quite complicated code to handle edge cases. On the other hand, converting to `camelCase`, `PascalCase`, `snake_case`, etc could be handled in YAML more efficiently.

Something like:

```yaml
variables:
  rgName: eu-github-actions-runners-t
  sanitizedName: # Should become 'eugithubactionsrunnerst'
    Fn::Slugify: ${rgName}
  storageName: ${sanitizedName}-st
```

Slugify would by default remove all non-alphabetic characters and lowercase the result. We could probably start with a simple mode and default to "lowercase", and consider adding modes like `kebab-case` or `snake_case` and others as needed.

**Comment by BoSoeborgPetersen** [comment]
For this specific use case it would suffice, but I think a replace function will become necessary for other use cases.

Here are some of mine in c#, which I might want to do with Pulumi Yaml in the future:
```
var endpointOrigin = storageAccount.PrimaryEndpoints.Apply(pe => pe.Blob.Replace("https://", "").Replace("/", ""));
```

```
Name = endpointOrigin.Apply(n => n.Replace('.', '-')),
```            
And this could be done with Regex replace, but I think it would help a lot of people with a simple replace function, that replaces one string with another string for all occurrences.

**Comment by AaronFriel** [comment]
Thanks for that example, that makes sense.

Each time we implement a new `Fn::` we need to make that work with `pulumi convert` to 5 or more languages, so we really want to make sure we're making the right choice for each function. Every additional function is just a little more overhead for our SDKs and complexity in our codegen, after all.

**Comment by BoSoeborgPetersen** [comment]
Okay, I see why you want to limit the number of functions then, but I really think that the most important functions will make the difference between having to use another Pulumi language and being able to use Pulumi Yaml for a use case.
This use case could be covered by Regex functions, but that does make it harder for a lot of people, which I my case means that it will be harder for me to convince the IT people to switch from Terraform.

**Comment by AaronFriel** [comment]
@BoSoeborgPetersen that's a compelling argument 😄 

Are there any other use cases you've found where text replacement was necessary for you to use YAML? The more examples we have where something isn't usable in YAML, the higher this will be on our list to address.

**Comment by davidhiebert** [comment]
FWIW, I ran into a need to string replacement today and ended up created a Command resource to use `sed`. The use case is referencing an OIDC provider from an `eks:getCluster`, which only provides the URL of the OIDC.  This needs a string replacement in order to apply to an IAM Role Trust policy.

Having tried `aws-iam:index:AssumableRoleWithOIDC` which panics with the provided example first.

**Comment by AaronFriel** [comment]
@davidhiebert what's the before and after of that string look like? That sounds like it may be a different kind of "replace" than the previous.

I'd like to get more information on the use cases before we commit to a function and its semantics. It's not too hard to implement many additional functions in YAML, but supporting `pulumi convert` requires building that implementation in several other languages. That's a lot of overhead to maintain, and if we get it wrong - `Fn::Replace` works for your use case but not someone else's - then we have to implement two functions, or more, as we find more of these cases.

Until then, I recommend using `pulumi convert` as a workaround here.

**Comment by davidhiebert** [comment]
@AaronFriel In my use case, I am simply looking for a String Replacement or a split function. In the case of an EKS cluster, the only useful information for the OIDC provider is the issuer URI: `https://oidc.eks.us-east-1.amazonaws.com/id/<OIDC_IDENTIFIER>`, when the IAM Role's trusted policy needs something that looks like this:

`arn:aws:iam::${callerIdentity.accountId}:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/<OIDC_IDENTIFIER>`

Since it would seem that `local:Command` doesn't seem to compatible with being run in a Variable, I did so in a resource like so:

```
  oidcID:
    type: command:local:Command
    properties:
      triggers:
        - "${oidcUri}"
      create: "echo ${oidcUri} | cut -d/ -f5 | tr -d '\n'"
      update: "echo ${oidcUri} | cut -d/ -f5 | tr -d '\n'"
```

Then refer to it later as:
`"arn:aws:iam::${callerIdentity.accountId}:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/${oidcID.stdout}"`

I'd prefer to use native functions, than calling out to a shell.

**Comment by AaronFriel** [comment]
@davidhiebert I think `Fn::Split` may serve your needs as well in pure YAML, as long as you know the prefix, I think this may work:

```
variables:
  oidcId: 
    Fn::Select:
      - 1
      - Fn::Split: ["https://oidc.eks.us-east-1.amazonaws.com/id/", ${oidcUri}]
  oidcArn: arn:aws:iam::${callerIdentity.accountId}:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/${oidcId}
```

You mentioned a panic with `aws-iam:index:AssumableRoleWithOIDC` though, is that related to trying to do the above? If there is a panic, we'll want to flag that as a P0 to address.

**Comment by davidhiebert** [comment]
@AaronFriel Thank you very much, I'll give that a shot.  Where can I find this documented?  Even knowing the names of the functions now, I cannot find reference to them in regards to Pulumi.

The Panic I ran into would have been an apparently "more native" way to handle it, without functions.  Unfortunately, since that resource type panics, I had to revert back to `aws:iam:Role` resource.

**Comment by AaronFriel** [comment]
@davidhiebert our mistake, looks like we implemented and failed to add it to the README.

In the near future we'll be moving our Pulumi YAML spec (almost everything in the README of the repo) to the website, I think we haven't yet made the switch.

**Comment by iwahbe** [comment]
We have decided to not add `Fn::Replace` to the language. Each function added imposes a cost on Pulumi YAML, and because of `pulumi convert` each other language we support. Some functions (regexp engines, for [example](https://github.com/pulumi/pulumi-yaml/issues/226)) do not translate cleanly into different languages. 

The solution we came up with is bundling utility functions into providers. For string manipulation functions, we have the [pulumi-str](https://github.com/pulumi/pulumi-str) provider. 

Going back to the original example, this is our recommended solution:
```yaml
variables:
  rgName: eu-github-actions-runners-t
  sanitizedName: # Should become 'eugithubactionsrunnerst'
    Fn::str:replace:
      string: ${rgName}
      old: '-'
      new: ''
outputs:
  storageName: ${sanitizedName.result}-st
```
```
Outputs:
    storageName: "eugithubactionsrunnerst-st"
```
