### ISSUE TITLE
Multiple files for Yaml resources

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [pulumi/pulumi-yaml#227]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I would like to avoid files getting too long, so I would like to split my resources over multiple files, either by using some kind of import statement in the main file, that points to other files like:

**Pulumi.yaml:**
```
name: github-actions-runners-cluster
runtime: yaml
description: GitHub Actions Runners Cluster

resources:
  resourceFile: container.yaml
  resourceGroup:
    type: azure-native:resources:ResourceGroup
```
**Container.yaml**
```
resources:
  registry:
    type: azure-native:containerregistry:Registry
  workspace:
    type: azure-native:operationalinsights:Workspace
  managedCluster:
    type: azure-native:containerservice:ManagedCluster
```

Or implicitly by including everything from all files in a folder called "resources", in addition to the main yaml file.
Or both?
