### ISSUE TITLE
Support  in Fn::Join

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#240]
In YAML like the example below, an error is thrown that the second argument must be a list. This isn't true, we can relax it like we have other functions to allow any expression, so long as that expression evaluates to a list.

```yaml    
variables:
  certificateChainPem: 
    Fn::Join:
      - "\n"
      - ${certificate.chainCertPems}
```

Error: `the second argument to Fn::Join must be a list; the second argument to Fn::Join must be a list`
