### ISSUE TITLE
Unable to reference SNS Topic's ARN with YAML in 3.34.0

### ISSUE THREAD

**Issue by kevholmes** [pulumi/pulumi-yaml#247]
### What happened?

We are utilizing Pulumi's YAML functionality to deploy a simple Step Function/Lambda stack. We create an AWS SNS topic, and then add a subscription. When we add a subscription, we reference the SNS Topic's ARN. This worked previously in 3.33.2 but now throws the following error in 3.34.0:

```bash
Diagnostics:
  pulumi:pulumi:Stack (srem-loadbalancer-automation-infra-dev-admin_us-east-2):
    error: Union<string, aws:sns/topic:Topic> is not assignable from aws:index/aRN:ARN
    
      on Pulumi.yaml line 210:
     210:       topic: ${snsNotificationTopic.arn}
    
    Cannot assign 'aws:index/aRN:ARN' to type 'Union<string, aws:sns/topic:Topic>':
      Cannot assign 'aws:index/aRN:ARN' to type 'string'
      Cannot assign 'aws:index/aRN:ARN' to type 'string'
```

### Steps to reproduce

```yaml
name: my-stack
runtime: yaml
description: aws stack

resources:
  snsNotificationTopic:
    type: aws:sns:Topic
    properties:
      name: loadbalancer-automation-sns-topic
      kmsMasterKeyId: alias/aws/sns
  snsNotificationSubscriptionKevin:
    type: aws:sns:TopicSubscription
    properties:
      endpoint: "validaddress@email.com"
      protocol: email
      topic: ${snsNotificationTopic.arn}
```

### Expected Behavior

An SNS Topic to be created, and an email subscription to be attached.

### Actual Behavior

`pulumi up` errors out when parsing the YAML

### Versions used

*Version that works*
```
❯ pulumi about
CLI          
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           kholmes-xps
URL            s3://tls-policy-automation-infra-dev-admin-us-east-2
User           kholmes
Organizations
```

*Version that's broken*

```
❯ pulumi about
CLI          
Version      3.34.0
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in yaml

Backend        
Name           kholmes-xps
URL            s3://tls-policy-automation-infra-dev-admin-us-east-2
User           kholmes
Organizations
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
