### ISSUE TITLE
Consider sugar for `Fn::Invoke`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#288]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We would like to make it more ergonomic to call invokes. We should consider adding the following sugar:
```yaml
Fn::pkg:module:Name:
  Arg1: ${Arg1}
  Arg2: ${Arg2}
# Would be equivalent to:
Fn::Invoke:
  Function: pkg:module:Name
  Arguments:
    Arg1: ${Arg1}
    Arg2: ${Arg2}
```

This will make invokes similar in calling convention to our built-in functions. 

Upsides:
- Unifies invoke and builtin fn syntax
- Simplifies syntax, loosing a level of indentation

Downsides:
- We will still need to support the `Fn::Invoke` syntax, since it is necessary for supplying invoke options.
- More ways of doing things and more surface area for us.
