### ISSUE TITLE
Support provider default version setting along with `providers` project config

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#293]
We'd like an example demonstrating that we can set the default provider version for invokes & resources within a program.

This repo uses AWS v4 in examples, we could create an example that sets the version to v5 and uses BucketV2. We could also find a deprecated/removed resource from another package and prove that we can acquire that and use it via default versioning.

For an EKS example, it would be interesting to set a default provider that uses the kubernetes config and uses that to create a namespace in the cluster.

Syntax should be similar to:

```yaml
resources:
  eks:
    type: eks:Cluster
  kubernetes:
    type: pulumi:pulumi:kubernetes
    defaultProvider: true
    properties:
      kubeconfig: ${eks.kubeconfig} # depends on EKS!
      enableServerSideApply: true
    options:
      version: 3.20
```
