### ISSUE TITLE
Convert - Generated Go Program Contains Undefined `GetFloat` Method on Pulumi Configuration

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-yaml#306]
### What happened?

Generated go program contains undefined Pulumi Configuration method `GetFloat`; Actual method is `GetFloat64`.

### Steps to reproduce

1. Create simple Pulumi yaml program with below definition.
```yaml
name: yaml-config-convert
runtime: yaml
description: A minimal Pulumi YAML program

configuration: 
  numberVal:
    type: Number
    default: 30
```
2. `pulumi convert --language go --out ./go`
3. See generated configuration access (`cfg.GetFloat`).
```golang
package main

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		cfg := config.New(ctx, "")
		numberVal := 30
		if param := cfg.GetFloat("numberVal"); param != 0 {
			numberVal = param
		}
		return nil
	})
}
```

### Expected Behavior

Configuration access should utilize `GetFloat64` method.

### Actual Behavior

`GetFloat` method (undefined) is used.

### Additional context

Note: using a non-default value results in the same scenario for `RequireFloat` (should be `RequireFloat64`).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
