### ISSUE TITLE
Convert - (Typescript) Providers are Incorrectly Referenced with Non Pulumi Owned Provider Packages

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-yaml#309]
### What happened?

Non-Pulumi owned Provider packages are incorrectly referenced in typescript programs.
Eg- https://github.com/EventStore/pulumi-eventstorecloud

### Steps to reproduce

Install plugin:
`pulumi plugin install resource eventstorecloud v0.2.3 \
  --server https://github.com/EventStore/pulumi-eventstorecloud/releases/download/v0.2.3`

Create new program:
`pulumi new yaml`

Replace Pulumi.yaml with:
```yaml
name: yaml-config-convert
runtime: yaml
description: A minimal Pulumi YAML program

#configuration: 
#variables:     {}
resources:
  eventStoreProvider:
    type: pulumi:providers:eventstorecloud
#outputs:       {}
```

Convert to typescript:
`pulumi convert --generate-only --language typescript --out ./nodejs`

### Expected Behavior

Program emitted:
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as eventstorecloud from "@eventstore/pulumi-eventstorecloud";

const eventStoreProvider = new eventstorecloud.Provider("eventStoreProvider", {});
```

### Actual Behavior

Program emitted:
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as pulumi_eventstorecloud from "@eventstore/pulumi-eventstorecloud";

// import is prepended with `pulumi_` which causes compiler error.
const eventStoreProvider = new eventstorecloud.Provider("eventStoreProvider", {});
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
