### ISSUE TITLE
Convert - Go Program Generated with Malformed Import Statements

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-yaml#311]
### What happened?

Generating a go program which includes non-Pulumi owned Provider Packages, results in malformed import statements _sometimes_. Eg- In the example below the eventstorecloud import statement incorrectly inserts `pulumi` as the repo, however, the grapl-security import statement is correctly generated.

### Steps to reproduce

Install eventstorecloud and grapl-security plugins:
`pulumi plugin install resource eventstorecloud v0.2.3 --server https://github.com/EventStore/pulumi-eventstorecloud/releases/download/v0.2.3`
`pulumi plugin install resource grapl-security [version] --server https://github.com/grapl-security/pulumi-hcp/releases/download/v[version]`

Create new program:
`pulumi new yaml`

Replace Pulumi.yaml with:
```yaml
name: yaml-config-convert
runtime: yaml
description: A minimal Pulumi YAML program

#configuration: 
#variables:     {}
resources:
  eventStoreProvider:
    type: pulumi:providers:eventstorecloud
  graplProvider:
    type: pulumi:providers:hcp
#outputs:       {}
```

Convert to go:
`pulumi convert --generate-only --language go --out ./go`

### Expected Behavior

Import statements are generated correctly for all providers.

### Actual Behavior

grapl-security import statement is correctly generated, however, the eventstorecloud import statement is malformed (it's treated as if it's located in a Pulumi repo):
```go
package main

import (
	"github.com/grapl-security/pulumi-hcp/sdk/go/hcp"
	"github.com/pulumi/pulumi-eventstorecloud/sdk/go/eventstorecloud"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := eventstorecloud.NewProvider(ctx, "eventStoreProvider", nil)
		if err != nil {
			return err
		}
		_, err = hcp.NewProvider(ctx, "graplProvider", nil)
		if err != nil {
			return err
		}
		return nil
	})
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
