### ISSUE TITLE
Convert - Generated Go Program has Incorrect Import Statement for Non-Pulumi Owned Providers w/ Non-Primitive Arguments

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-yaml#314]
### What happened?

Pulumi-yaml convert generates duplicate, invalid imports for go programs when a non-Pulumi owned provide package is used. More specifically, this occurs only when the provider's constructor has non-primitive arguments.

### Steps to reproduce

1. Create simple Pulumi yaml program with below definition.
```yaml
name: yaml-config-convert
runtime: yaml
description: A minimal Pulumi YAML program
resources:
  proxmoveProvider:
    type: pulumi:providers:proxmoxve
    properties:
      virtualEnvironment:
        endpoint: some-endpoint
        insecure: false
        otp: super-secret-stuff
        password: also-secret-stuff
        username: userdude
```
2. This requires a provide plugin which takes non-primitive arguments to be installed: `pulumi plugin install resource proxmoxve v2.0.0 \
  --server https://github.com/muhlba91/pulumi-proxmoxve/releases/download/v2.0.0`
3. `pulumi convert --generate-only --language go --out ./go`
4. See generated output
```go
package main

import (
	"github.com/muhlba91/pulumi-proxmoxve/sdk/v2/go/proxmoxve"
        // pulumi-yaml injects this invalid, nonsense package when it encounters a non-primitive provider argument
	"github.com/pulumi/pulumi-proxmoxve/sdk/v2/go/proxmoxve"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := proxmoxve.NewProvider(ctx, "proxmoveProvider", &proxmoxve.ProviderArgs{
			VirtualEnvironment: &ProviderVirtualEnvironmentArgs{
				Endpoint: pulumi.String("some-endpoint"),
				Insecure: pulumi.Bool(false),
				Otp:      pulumi.String("super-secret-stuff"),
				Password: pulumi.String("also-secret-stuff"),
				Username: pulumi.String("userdude"),
			},
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

### Expected Behavior

All imports are generated correctly.

### Actual Behavior

Invalid, nonsense import is generated.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
