### ISSUE TITLE
`pulumi convert` panics with certain YAML expressions

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-yaml#317]
Given the following source file, which uses `Fn::Split` and `Fn::Select` to pull a portion of a string out of an output so it can be passed to another resource as an input:

```yaml
name: templates-static-website-azure-yaml
runtime: yaml
description: A static website on Azure

configuration:
  path:
    type: String
    default: ./site
  indexDocument:
    type: String
    default: index.html
  errorDocument:
    type: String
    default: error.html

# 👇
variables:
  originHostname:
    Fn::Select:
      - 2
      - Fn::Split:
        - /
        - ${account.primaryEndpoints.web}

resources:

  resource-group:
    type: azure-native:resources:ResourceGroup

  account:
    type: azure-native:storage:StorageAccount
    properties:
      resourceGroupName: ${resource-group.name}
      kind: StorageV2
      sku:
        name: Standard_LRS

  website:
    type: azure-native:storage:StorageAccountStaticWebsite
    properties:
      resourceGroupName: ${resource-group.name}
      accountName: ${account.name}
      indexDocument: ${indexDocument}
      error404Document: ${errorDocument}

  synced-folder:
    type: synced-folder:index:AzureBlobFolder
    properties:
      path: ${path}
      resourceGroupName: ${resource-group.name}
      storageAccountName: ${account.name}
      containerName: ${website.containerName}

  profile:
    type: azure-native:cdn:Profile
    properties:
      resourceGroupName: ${resource-group.name}
      sku:
        name: Standard_Microsoft

  endpoint:
    type: azure-native:cdn:Endpoint
    properties:
      resourceGroupName: ${resource-group.name}
      profileName: ${profile.name}
      isHttpAllowed: false
      isHttpsAllowed: true
      isCompressionEnabled: true
      contentTypesToCompress:
        - text/html
        - text/css
        - application/javascript
        - application/json
        - image/svg+xml
        - font/woff
        - font/woff2
      originHostHeader: ${originHostname}  # 👈
      origins:
        - name: ${account.name}
          hostName: ${originHostname}  # 👈

outputs:
  originURL: ${account.primaryEndpoints.web}
  cdnURL: https://${endpoint.hostName}
```

.. `pulumi convert` panics in the following way:

```bash
$ pulumi convert --out "$somelang" --language "$somelang"

================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.38.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: A failure has occurred: unexpected builtin type *ast.SplitExpr
```
