### ISSUE TITLE
codegen - load.go missing int types

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-yaml#328]
### What happened?

`load.go` is missing recently introduced int types.

https://github.com/pulumi/pulumi-yaml/blob/342b902b3a4800f6d78ed63971f39e4bcf683479/pkg/pulumiyaml/codegen/load.go#L463-L476

### Steps to reproduce

```
name: pulumi-yaml-convert
runtime: yaml
description: A minimal Pulumi YAML program

configuration: 
  numberVal:
    type: Number
    default: 30
  intValue:
    type: Int
    default: 30
```

`pulumi convert --language go --generate-only --out ./go`

### Expected Behavior

Int is an accepted type.

### Actual Behavior

error - `unrecognized type 'Int' for config variable ...`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
