### ISSUE TITLE
[convert] - Incorrect go imports generated for non-pulumi owned package

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-yaml#335]
### What happened?

`pulumi convert....` generates duplicate, invalid imports for go programs when non-Pulumi owned package is used. This is the same outcome as #314. 

### Steps to reproduce

1. Create simple Pulumi yaml program
```
name: yaml-config-convert
runtime: yaml
description: A minimal Pulumi YAML program
resources: 
  vm:
    type: proxmoxve:VM:VirtualMachine
    properties: 
      disks:
        - interface: blah
          datastoreId: foo
          size: 32
          fileFormat: bar
```
2. This requires a provide plugin which takes non-primitive arguments to be installed: `pulumi plugin install resource proxmoxve v2.0.0 \ --server https://github.com/muhlba91/pulumi-proxmoxve/releases/download/v2.0.0`
3. `pulumi convert --generate-only --language go --out ./go`

### Expected Behavior

Correct go imports

### Actual Behavior

Invalid go import is generated when the `disks` property is encountered.

```
package main

import (
	"github.com/muhlba91/pulumi-proxmoxve/sdk/v2/go/proxmoxve/VM"
	"github.com/pulumi/pulumi-proxmoxve/sdk/v2/go/proxmoxve/VM"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := VM.NewVirtualMachine(ctx, "vm", &VM.VirtualMachineArgs{
			Disks: vm.VirtualMachineDiskArray{
				&vm.VirtualMachineDiskArgs{
					Interface:   pulumi.String("blah"),
					DatastoreId: pulumi.String("foo"),
					Size:        pulumi.Int(32),
					FileFormat:  pulumi.String("bar"),
				},
			},
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
