### ISSUE TITLE
`fromBase64`, `toBase64` does not convert corresponding code

### ISSUE THREAD

**Issue by aq17** [pulumi/pulumi-yaml#337]
### What happened?

Running `pulumi convert` from YAML to Go does not generate variables that use `fromBase64` or `toBase64`

### Steps to reproduce

Run `pulumi up` on 
```
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: yaml
template:
  description: A YAML document to create a Kubernetes cluster on Azure
  important: true
  config:
    azure-native:region:
      default: westus2
      description: The Azure region in which to create the cluster
configuration:
  numWorkerNodes:
    type: Number
    default: 3
  azureLocation:
    type: String
    default: westus2
  prefixForDns:
    type: String
    default: pulumi
  kubernetesVersion:
    type: String
    default: 1.24.3
  azureVmSize:
    type: String
    default: Standard_DS2_v2
  mgmtGroupId:
    type: String
  sshPubKey:
    type: String
resources:
  resourceGroup:
    type: azure-native:resources:ResourceGroup
    properties:
      location: ${azureLocation}
      resourceGroupName: aks-rg
  virtualNetwork:
    type: azure-native:network:VirtualNetwork
    properties:
      addressSpace:
        addressPrefixes:
          - 10.0.0.0/16
      location: ${azureLocation}
      resourceGroupName: ${resourceGroup.name}
      subnets:
        - addressPrefix: 10.0.0.0/24
          name: aks-subnet-1
        - addressPrefix: 10.0.1.0/24
          name: aks-subnet-2
        - addressPrefix: 10.0.2.0/24
          name: aks-subnet-3
      virtualNetworkName: aks-vnet
  managedCluster:
    type: azure-native:containerservice:ManagedCluster
    properties:
      aadProfile:
        enableAzureRBAC: true
        managed: true
        adminGroupObjectIDs:
          - ${mgmtGroupId}
      addonProfiles: {}
      agentPoolProfiles:
        - count: ${numWorkerNodes}
          enableNodePublicIP: false
          mode: System
          name: systempool
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: ${azureVmSize}
      dnsPrefix: ${prefixForDns}
      enableRBAC: true
      identity:
        type: SystemAssigned
      kubernetesVersion: ${kubernetesVersion}
      linuxProfile:
        adminUsername: azureuser
        ssh:
          publicKeys:
            - keyData: ${sshPubKey}
      location: ${azureLocation}
      networkProfile:
        networkPlugin: azure
        networkPolicy: azure
        serviceCidr: 10.96.0.0/16
        dnsServiceIP: 10.96.0.10
      resourceGroupName: ${resourceGroup.name}
      resourceName: aks-cluster
variables:
  aksCredentials:
    Fn::Invoke:
      Function: azure-native:containerservice:listManagedClusterUserCredentials
      Arguments:
        resourceGroupName: ${resourceGroup.name}
        resourceName: ${managedCluster.name}
  actualKubeConfig:
    Fn::FromBase64: ${aksCredentials.kubeconfigs[0].value}
outputs:
    # Export the Kubeconfig of the cluster
    clusterName: ${managedCluster.name}
    kubeconfig: ${actualKubeConfig}

```
### Expected Behavior

Generated go code would include a variable for `actualKubeConfig`

### Actual Behavior

`actualKubeConfig` variable is missing, so program exports a non-existent variable 

### Output of `pulumi about`

```
CLI          
Version      3.41.0-dev.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown

Host     
OS       darwin
Version  12.4
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.19 darwin/arm64'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aqiu
User           aqiu
Organizations  aqiu, pulumi

No dependencies found
```

### Additional context

Discovered after patching panic for https://github.com/pulumi/pulumi/issues/10726

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
