### ISSUE TITLE
Typechecker doesn't enforce required properties at the top level

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#349]
### What happened?

The type checker allows resources with missing properties to type check.

### Steps to reproduce

Run `pulumi up` on 

```yaml
name: yaml-test
runtime: yaml
description: A minimal Pulumi YAML program
resources:
  bucket:
    type: aws:s3:BucketObject
```

### Expected Behavior

Type error: `bucket` is missing required property `bucket`.

### Actual Behavior

Program type checks.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
