### ISSUE TITLE
Support calling resource methods

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#354]
It is almost possible to call resource methods manually, as in this program which calls the "getKubeconfig" method on cluster:

```yaml
variables:
  kubeconfig:
    Fn::Invoke:
      Function: google-native:container/v1:Cluster/getKubeconfig
      Arguments:
        __self__: ${someClusterResource}
```

However, this generates an `Invoke`, not a `Call` RPC. The syntax also leaves something to be desired, with the `__self__` parameter being an implementation detail that other Pulumi languages do not expose to users.

**Comment by lukehoban** [comment]
The simplest “raw” thing to do might be to just expose the Call concept directly (much like we do for Invoke today)?

```
variables:
  kubeconfig:
    Fn::Call:
      Function: google-native:container/v1:Cluster/getKubeconfig
      Self: ${someClusterResource}
      Arguments:
        …
```

Are there other more “sugar” options worth considering?

**Comment by viveklak** [comment]
Just adding a note that we would also need to add support for the above in docs gen: https://github.com/pulumi/pulumi-google-native/issues/709

**Comment by justinvp** [comment]
> Are there other more “sugar” options worth considering?

I don't love it, but maybe something like the following, where you only have to specify the resource instance and name of the method?

```yaml
variables:
  kubeconfig:
    Fn::Method:
      Resource: ${someClusterResource}
      Method: getKubeconfig
      Arguments:
        ...
```

Or could we get fancy and grab the method out of the expression:

```yaml
variables:
  kubeconfig:
    Fn::Method:
      Method: ${someClusterResource.getKubeconfig}
      Arguments:
        ...
```
