### ISSUE TITLE
We don't convert numeric literals to strings when appropriate

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#364]
### What happened?

We failed to convert an example from pu/pu.

### Steps to reproduce

Attempt to convert example

### Expected Behavior

```yaml
resources:
  bucket:
    type: aws:s3:Bucket
variables:
  encoded:
    fn::toBase64: haha business
  decoded:
    fn::fromBase64: ${encoded}
  joined:
    fn::join:
      - '-'
      - - ${encoded}
        - ${decoded}
        - '2'
  encoded2:
    fn::toBase64: ${bucket.id}
  decoded2:
    fn::fromBase64: ${bucket.id}
```

### Actual Behavior

```yaml
resources:
  bucket:
    type: aws:s3:Bucket
variables:
  encoded:
    fn::toBase64: haha business
  decoded:
    fn::fromBase64: ${encoded}
  joined:
    fn::join:
      - '-'
      - - ${encoded}
        - ${decoded}
        - 2
  encoded2:
    fn::toBase64: ${bucket.id}
  decoded2:
    fn::fromBase64: ${bucket.id}
```

This generates an error since `fn::join` requires a list of strings.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
