### ISSUE TITLE
`pulumi convert` turns references to resources into `res.id` which is not valid in other languages 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-yaml#386]
Creating the default `pulumi new serverless-aws-yaml` and then `pulumi convert --language typescript --out ./ts` succeeds - but then fails to typescheck in TS with:

```console
reviewing update (dev)

View Live: https://app.pulumi.com/lukehoban/demo2/dev/previews/158d94d9-3fcb-4d19-871c-0bf40984b85b

     Type                 Name       Plan     Info
     pulumi:pulumi:Stack  demo2-dev           1 error
 
Diagnostics:
  pulumi:pulumi:Stack (demo2-dev):
    error: Running program '/Users/lukehoban/dd/ced2022demos/demo2/demo2ts' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(32,9): error TS2322: Type 'Output<string>' is not assignable to type 'Input<Function> | undefined'.
      Type 'Output<string>' is not assignable to type 'OutputInstance<Function>'.
        Types of property 'apply' are incompatible.
          Type '{ <U>(func: (t: string) => Promise<U>): Output<U>; <U>(func: (t: string) => OutputInstance<U>): Output<U>; <U>(func: (t: string) => U): Output<...>; }' is not assignable to type '{ <U>(func: (t: Function) => Promise<U>): Output<U>; <U>(func: (t: Function) => OutputInstance<U>): Output<U>; <U>(func: (t: Function) => U): Output<...>; }'.
            Types of parameters 'func' and 'func' are incompatible.
              Types of parameters 't' and 't' are incompatible.
                Type 'string' is not assignable to type 'Function'. 
```

Similar code is generated in other languages - which will similarly not typecheck correctly for them.

The issue is that this:

```yaml
eventHandler: ${fn}
```

Becomes this:

```ts
eventHandler: fn.id,
```

But should be this:

```ts
eventHandler: fn,
```

**Comment by Zaid-Ajaj** [comment]
For more context on the problem:

<details>
<summary>The Pulumi YAML program</summary>

```yaml
name: serverlesstest
description: A serverless app on AWS API Gateway and Lambda
runtime: yaml
resources:
    # An execution role to use for the Lambda function
    role:
        type: aws:iam:Role
        properties:
            assumeRolePolicy:
                Fn::ToJSON:
                    Version: 2012-10-17
                    Statement:
                        - Action: sts:AssumeRole
                          Effect: Allow
                          Principal:
                            Service: lambda.amazonaws.com
            managedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    # A Lambda function to invoke
    fn:
        type: aws:lambda:Function
        properties:
            runtime: python3.9
            handler: handler.handler
            role: ${role.arn}
            code:
                Fn::FileArchive: ./function
    # A REST API to route requests to HTML content and the Lambda function
    api:
        type: aws-apigateway:RestAPI
        properties:
            routes:
                - path: /
                  localPath: www
                - path: /date
                  method: GET
                  eventHandler: ${fn}
outputs:
    # The URL at which the REST API will be served.
    url: ${api.url}
```

</details>

<details>
<summary>The generated PCL program</summary>

```
resource role "aws:iam/role:Role" {
	__logicalName = "role"
	assumeRolePolicy = toJSON({
		"Version" = "2012-10-17",
		"Statement" = [{
			"Action" = "sts:AssumeRole",
			"Effect" = "Allow",
			"Principal" = {
				"Service" = "lambda.amazonaws.com"
			}
		}]
	})
	managedPolicyArns = ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
}

resource fn "aws:lambda/function:Function" {
	__logicalName = "fn"
	runtime = "python3.9"
	handler = "handler.handler"
	role = role.arn
	code = fileArchive("./function")
}

resource api "aws-apigateway:index:RestAPI" {
	__logicalName = "api"
	routes = [
		{
			path = "/",
			localPath = "www"
		},
		{
			path = "/date",
			method = "GET",
			eventHandler = fn.id
		}
	]
}

output url {
	__logicalName = "url"
	value = api.url
}

```

</details>

It looks like the problem is not so much in codegen from pulumi/pulumi but rather from pulumi-yaml when converting the template into PCL
