### ISSUE TITLE
Docs are generated with old `Fn` syntax

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#399]
### What happened?

We are generating docs like https://www.pulumi.com/registry/packages/aws/api-docs/acmpca/getcertificate/:
```yaml
variables:
  example:
    Fn::Invoke:
      Function: aws:acmpca:getCertificate
      Arguments:
        arn: arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/12345678-1234-1234-1234-123456789012/certificate/1234b4a0d73e2056789bdbe77d5b1a23
        certificateAuthorityArn: arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/12345678-1234-1234-1234-123456789012
```

### Steps to reproduce

Look at the documentation of any invoke.

### Expected Behavior

Functions should be generated with the new camelCase syntax.

### Actual Behavior

Functions are generated with the old CamelCase syntax.

### Additional context

Issue was originally brought up via https://pulumi.slack.com/archives/C85BS3LJZ/p1667558918008279.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
