### ISSUE TITLE
Beta plugin versions are used over stable versions

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-yaml#414]
### What happened?

When running a program when having the follwing plugins installed:

```
    resource awsx-1.0.0
    resource awsx-1.0.0-beta.11
```

The YAML language used the beta package instead of the stable and newer `1.0.0` package.

### Steps to reproduce

1. `pulumi plugin install resource awsx 1.0.0-beta.11`
2. `pulumi plugin install resource awsx 1.0.0`
3. Attempt to run the following program

```yaml
resources:
  cluster:
    type: aws:ecs:Cluster
  lb:
    type: awsx:lb:ApplicationLoadBalancer
  service:
    type: awsx:ecs:FargateService
    properties:
      cluster: ${cluster.arn}
      assignPublicIp: true
      desiredCount: 2
      taskDefinitionArgs:
        container:
          image: nginx:latest
          cpu: 512
          memory: 128
          essential: true
          portMappings:
            targetGroup: ${lb.defaultTargetGroup}
```
 

### Expected Behavior

Should use 1.0.0 and pass correctly

### Actual Behavior

Fails with error due to property not existing in beta version

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hey @danielrbradley , it looks like this isn't actually a plugin issue. `portMappings` [is an array](https://github.com/pulumi/pulumi-awsx/blob/master/awsx/schema.json#L1041-L1045) – changing it to 
```
          portMappings:
            - targetGroup: ${lb.defaultTargetGroup}
```
seems to work.

**Comment by danielrbradley** [comment]
Yes, that does look like a typo there too, although the error I was seeing was actually complaining about `assignPublicIp` not existing (which was new in 1.0.0)

**Comment by aq17** [comment]
Hm I didn't see that error, even after removing `1.0.0` and only having `1.0.0-beta.11` installed

**Comment by danielrbradley** [comment]
Hmm, perhaps there's some kind of caching going on as that program is correctly invalid for `1.0.0-beta.11` and should fail.

**Comment by aq17** [comment]
@danielrbradley apologies but I'm still unable to repro, even when explicitly using the beta version i.e. 
```
resources:
  awsx: 
    type: pulumi:providers:awsx
    defaultProvider: true
    options:
      version: 1.0.0-beta.11
```
Would be super helpful if we could sync on this next week and try to root cause the issue.
