### ISSUE TITLE
Allow `docker:Image` as a resource for docker v4+ 

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-yaml#421]
## YAML workaround

To use Docker image resources, declare a default provider to use the v4 provider:

```
resources:
  docker-provider:
    type: pulumi:providers:docker
    defaultProvider: true
    options:
      version: 4.0.0-alpha.0
```

Refer to https://github.com/pulumi/pulumi-docker for the latest release version(s).

------------

Currently we [disallow Docker Image resource](https://github.com/pulumi/pulumi-yaml/blob/main/pkg/pulumiyaml/packages.go#L222) from being used with yaml.

As of pulumi-docker v4.0, this resource is schematized and therefore YAML compatible.

It was suggested we remove the error in favor of a warning, letting users know this resource will not work in YAML for pulumi-docker v3.x and lower.
