### ISSUE TITLE
feat: readFile - interpolate variables in external references to main Pulumi.yaml

### ISSUE THREAD

**Issue by terekete** [pulumi/pulumi-yaml#448]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- When using fn::readFile, if ${my_variable} parameters are found in external files dont get variable values defined from the Pulumi.yaml.

Example:

If I have two files, 1. Pulumi.yaml with fn:readfile function and 2. external file I would like to include on the Pulumi.yaml as:

1. Pulumi.yaml
```yaml
name: yaml_example
runtime: yaml
description: yaml_example

config:
  builder:
    type: string
  project:
    type: string

variables:
  location: northamerica-northeast1
  process_name: simple_process
  schema:
    fn::readFile: ./schema.json

resources:
  table:
    type: gcp:bigquery:Table
    properties:
      datasetId: my_dataset
      tableId: my_table
      deletionProtection: false
      description: "Example external table using CSV"
      externalDataConfiguration:
        autodetect: false
        sourceFormat: CSV
        sourceUris:
          - gs://my-bucket/*.csv
        schema: >
          ${schema}
        csvOptions:
          quote: '"'
          allowJaggedRows: true
          allowQuotedNewlines: true
          skipLeadingRows: 1
```

2. External file called schema.json:
```json
[
    {
        "name": "Username",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "${process_name} - Employee Username"
    }
]
```

${process_name} is being referenced from the main Pulumi.yaml file but it does not presently work to be passed or interpolated.

### Affected area/feature

The outcome that would be really amazing is if there was a version of the readFile that assembled the Pulumi.yaml and then did the interpolation of variable so external files can use them also.
