### ISSUE TITLE
Reference to a boolean config value is converted to a string when used

### ISSUE THREAD

**Issue by nstires-ctgx** [pulumi/pulumi-yaml#495]
### What happened?

When a config value is declared, and a default is passed, it's changing the type of the value to string. 

On `pulumi up`:
```
warning: Failed to get information about the plugin: failed to discover plugin requirements:
-error: Pulumi.yaml: protect must be a boolean value;
```

### Expected Behavior

Default value should be accepted and passed as bool.

### Steps to reproduce

Pulumi.yaml:
```
config:
  protect:
    default: false
    type: boolean
resources:
  network:
    type: gcp:compute:Network
    options:
      protect: ${protect}
```

Note that:

* hardcoding `true` or `false` in the resource option works as expected
* referencing a boolean configuration value in the resource option is what doesn't work

### Output of `pulumi about`

```
CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Host
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in yaml
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
