### ISSUE TITLE
Poor preview experience

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-yaml#51]
With this program:

```yaml
name: simple-s3
runtime: yaml
resources:
  bucket1:
    type: aws:s3/bucket:Bucket
  bucket2:
    type: aws:s3/bucket:Bucket
    properties:
      bucket: ${bucket1.bucket}222
```

Run `pulumi up` to deploy.  Then run `pulumi up` again - the preview shows:

```
$ pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/lukehoban/simple-s3/dev/previews/cf6475b1-cdff-412d-a843-5cc3516c57b9

     Type                 Name           Plan        Info
     pulumi:pulumi:Stack  simple-s3-dev              
 +-  └─ aws:s3:Bucket     bucket2        replace     [diff: ~bucket]
 
Resources:
    +-1 to replace
    2 unchanged

Do you want to perform this update?  [Use arrows to move, enter to select, type to filter]
  yes
> no
  details
```

Which is unexpected since nothing has changed.

Going ahead with the update, it shows (correctly) that nothing actually does need to change.

```
View Live: https://app.pulumi.com/lukehoban/simple-s3/dev/updates/7

     Type                 Name           Status     
     pulumi:pulumi:Stack  simple-s3-dev             
 
Resources:
    3 unchanged

Duration: 2s
```
