### ISSUE TITLE
YAML SDK does not honor schema-set Secrets

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-yaml#521]
### What happened?

During the upgrade to pulumi-gcp to v7.0.0, we schematized a few new Outputs as Secret.

When running `pulumi up` on a YAML program, these Secrets were written to Outputs in plaintext.

This does not occur with the equivalent program in Typescript, or Go (which I verified.)

### Example

```yaml
name: dev
runtime: yaml
description: A minimal Google Cloud Pulumi YAML program
outputs:
  bucketName: ${my-bucket.url}
  pulumiAllLabels: ${my-bucket.pulumiLabels} # this should be Secret
  resourceSetLabels: ${my-bucket.labels} # this should be Secret
resources:
  # Create a GCP resource (Storage Bucket)
  my-bucket:
    properties:
      location: EU
      labels:
        good: morning
        bad: things
    type: gcp:storage:Bucket
    options:
      provider: ${gcp-provider}
  gcp-provider:
    type: pulumi:providers:gcp
    properties:
      defaultLabels:
        hello: goodbye
        new: defaultlabel
      project: ${project}
```

Output of `pulumi preview`
```
@guin:gcp-labels🦉 pulumi up
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/guinevere-pulumi-corp/dev/dev/previews/905ab2de-9a79-459d-abf8-ebefbc9d0c36

     Type                     Name          Plan       
 +   pulumi:pulumi:Stack      dev-dev       create     
 +   ├─ pulumi:providers:gcp  gcp-provider  create     
 +   └─ gcp:storage:Bucket    my-bucket     create     

Outputs:
    bucketName       : output<string>
    pulumiAllLabels  : {
        bad  : "things"
        good : "morning"
        hello: "goodbye"
        new  : "defaultlabel"
    }
    resourceSetLabels: {
        bad : "things"
        good: "morning"
    }

Resources:
    + 3 to create

Do you want to perform this update?
```

### Output of `pulumi about`

```
CLI          
Version      3.88.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME  VERSION
gcp   unknown (local plugin version)
yaml  unknown
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
