### ISSUE TITLE
Arbitrary keys and code at base indent level after `resources:` does not throw warning or error

### ISSUE THREAD

**Issue by jamest-pin** [pulumi/pulumi-yaml#535]
### What happened?

I created two new resources in my Pulumi.yaml and pulumi seemed blind to them. `pulumi preview` showed no sign of them.
I was able to introduce arbitrary properties and there is no error.
 

### Example

To Reproduce:

1. Create valid `Pulumi.yaml` with at least one resource.
2. At the base indent left (far left) add any arbitrary text that is valid yaml syntax.
3.  Pulumi will ignore it. 
![image](https://github.com/pulumi/pulumi-yaml/assets/138646078/49ab3cd4-5507-41e6-9654-521cd5a68456)

e.g.
```yaml
# Pulumi.yaml

config: {}
variables: {}
resources:
  myResource:
      [...] # some valid config

whatever:
  youwant:
    - something
```

Instead pulumi ought to throw an error or a warning.

### Output of `pulumi about`

```
% pulumi about
CLI          
Version      3.96.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       darwin
Version  13.6.3
Arch     arm64

This project is written in yaml
```

### Additional context

https://pulumi-community.slack.com/archives/C03E69EQRD2/p1702879893055319

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
