### ISSUE TITLE
Invokes supporting returning a full result

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-yaml#57]
I need to get a full result object from an invoke, for instance

```yaml
variables:
  keys:
    Fn::Invoke:
      Function: azure-native:containerregistry:listRegistryCredentials
      Arguments:
        resourceGroupName: ${resourceGroup.name}
        registryName: ${registry.name}
      Return: ???
```

The `Return` attribute is currently required but there doesn't seem to be a value to return the result as-is.

Consider making the `Return` attribute optional (or maybe we don't need it at all with variables and interpolation available?).
