### ISSUE TITLE
gcp:monitoring:UptimeCheckConfig recreated (without change) everytime pulumi up runs

### ISSUE THREAD

**Issue by yuripallada-groupm** [pulumi/pulumi-yaml#570]
### What happened?

We have a `gcp:monitoring:UptimeCheckConfig` in our Pulumi yaml program, which succesfully deploys a UptimeCheck on GCP. However, everytime we do `pulumi up` it recreates this Uptime Check in GCP, while nothing changes about the resource.

This is the resource in our program:
`
  uptime-check:
    type: gcp:monitoring:UptimeCheckConfig
    properties:
      displayName: API Uptime Check
      timeout: 30s
      httpCheck:
        path: /healthcheck
        port: 443
        useSsl: true
        validateSsl: true
        acceptedResponseStatusCodes:
          - statusClass: STATUS_CLASS_2XX
      period: 300s
      monitoredResource:
        type: uptime_url
        labels:
          host: ${apiDomain}
`

Where the ${apiDomain} variable contains the domain of our API (e.g. api.ourdomain.com)

The pipeline outputs: 
`++ gcp:monitoring:UptimeCheckConfig uptime-check created replacement (2s) [diff: ~monitoredResource]`

The monitored resource hasn't changed between executions, so not sure why it feels like re-creating the resource.
Additionally, we have also tried hardcoding the ${apiDomain} variable, but that didn't solve the problem.

We have also compared the state files between each deployment and found that nothing has changed to the input parameters, and only the id, name and uptimeCheckId output values have changed (obviously, since it re-creates it every time).

Do you have an idea how we can prevent this from happening?

### Example

1. Create a gcp:monitoring:UptimeCheckConfig resource with a montioredResource:
`
  uptime-check:
    type: gcp:monitoring:UptimeCheckConfig
    properties:
      displayName: API Uptime Check
      timeout: 30s
      httpCheck:
        path: /healthcheck
        port: 443
        useSsl: true
        validateSsl: true
        acceptedResponseStatusCodes:
          - statusClass: STATUS_CLASS_2XX
      period: 300s
      monitoredResource:
        type: uptime_url
        labels:
          host: our.domain.com
`
2. Deploy the program using `pulumi up`
3. Deploy again using `pulumi up`. The uptime check in GCP will be replaced

### Output of `pulumi about`

pulumi version: 3.113.3
pulumi GCP plugin version: 7.19.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I tried this out and reproduced the behavior with the following program, after running `pulumi new gcp-yaml`:

```yaml
name: gpcuptimecheck
runtime: yaml
resources:
  uptime-check:
    type: gcp:monitoring:UptimeCheckConfig
    properties:
      displayName: API Uptime Check
      timeout: 30s
      httpCheck:
        path: /healthcheck
        port: 443
        useSsl: true
        validateSsl: true
        acceptedResponseStatusCodes:
          - statusClass: STATUS_CLASS_2XX
      period: 300s
      monitoredResource:
        type: uptime_url
        labels:
          host: our.domain.com
```

When looking at the preview, if I select details, I see the following diff:

<img width="893" alt="Screenshot 2024-05-05 at 10 42 24 PM" src="https://github.com/pulumi/pulumi-yaml/assets/710598/462b7f8c-3452-4cd1-ad52-38780c2de63a">

Looks like `monitoredResource.labels` is changing.

I was able to workaround this with the [`ignoreChanges`](https://www.pulumi.com/docs/concepts/options/ignorechanges/) resource option:

```yaml
    options:
      ignoreChanges:
        - monitoredResource.labels
```

Full program:

```yaml
name: gpcuptimecheck
runtime: yaml
resources:
  uptime-check:
    type: gcp:monitoring:UptimeCheckConfig
    properties:
      displayName: API Uptime Check
      timeout: 30s
      httpCheck:
        path: /healthcheck
        port: 443
        useSsl: true
        validateSsl: true
        acceptedResponseStatusCodes:
          - statusClass: STATUS_CLASS_2XX
      period: 300s
      monitoredResource:
        type: uptime_url
        labels:
          host: our.domain.com
    options:
      ignoreChanges:
        - monitoredResource.labels
```

Moving this to the GCP repository to see if this is a bug that needs to be fixed or if there's a better approach to working around.
