### ISSUE TITLE
StackReference outputs are incorrectly typed as string instead of any

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#599]
Suppose we have the following program, assuming that the stack reference's `subnets` property is an array of strings:

```yaml
resources:
  vpc:
    options: {}
    properties:
      name: some/vpc/stack
    type: pulumi:pulumi:StackReference
  eksCluster:
    properties:
      vpcConfig:
        subnetIds: ${vpc.outputs.subnets}
```

This program should succeed, as the `vpcConfig.subnetIds` input accepts an array of strings - however instead users will encounter an error in the analysis phase of running this program:

```
vpcConfig: Cannot assign '{subnetIds: string}' to 'aws:eks/ClusterVpcConfig:ClusterVpcConfig':
        subnetIds: Cannot assign type 'string' to type 'List<string>'
```
