### ISSUE TITLE
Encountering error/warning when attempting to use strongly typed configuration

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-yaml#606]
### What happened?

While attempting to leverage [strongly typed configuration](https://www.pulumi.com/docs/concepts/config/#strongly-typed-configuration) and pulumi-yaml I encountered a warning/error. 

## Repro

1. Run `pulumi preview` with the following setup

### Pulumi.yaml

```yaml
name: pulumi-config-troubleshooting
runtime: yaml
description: A minimal Yaml Pulumi program
config:
  subnets:
    type: array
    items:
      type: string
```

### Pulumi.dev.yaml

```yaml
config:
  pulumi-config-troubleshooting:subnets:
    - subnet2
```

### Warning message

```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-config-troubleshooting-dev):
    Warning: Field 'items' does not exist on Object 'config.subnets'
      on Pulumi.yaml line 7:
       7:     items:
    Existing fields are: 'name', 'type', 'secret', 'value', 'default'
```

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
