### ISSUE TITLE
panic when using runtime.options.compiler

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-yaml#609]
### What happened?

A user reported on [community Slack](https://pulumi-community.slack.com/archives/C01PF3E1B8V/p1723065992615119) an issue where running a program with a custom compiler option (to append multiple files -- very reasonable) results in a panic:

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x105819bb8]
    goroutine 74 [running]:
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.topologicallySortedResources.func3(0x14000370dc0)
    	/Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/sort.go:169 +0xe8
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.topologicallySortedResources.func3(0x1400030b540)
    	/Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/sort.go:192 +0x488
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.topologicallySortedResources(0x14000514f00, {0x106535100, 0x0, 0x1059f6548?})
    	/Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/sort.go:209 +0xdd0
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*Runner).setIntermediates(0x14000332500, {0x0?, 0x1?}, 0x1?, 0x0, 0x0)
    	/Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:792 +0x220
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*Runner).ensureSetup(0x14000332500, 0x0)
    	/Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:805 +0x3c
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*Runner).Run(0x14000332500, {0x105cd7370?, 0x14000389b00})
    	/Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:833 +0x64
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.GetReferencedPlugins(0x14000514f00)
    	/Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/packages.go:146 +0x1c8
    github.com/pulumi/pulumi-yaml/pkg/server.(*yamlLanguageHost).GetRequiredPlugins(0x14000385708?, {0x10553d104?, 0x40?}, 0x105ad91e0?)
    	/Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/server/server.go:94 +0xac
    github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GetRequiredPlugins_Handler.func1({0x105cd49e8, 0x14000210c30}, {0x105c12cc0?, 0x14000100cc0})
    	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.123.1-0.20240711160144-b8226b705890/proto/go/language_grpc.pb.go:311 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x105cd49e8, 0x140001b49f0}, {0x105c12cc0, 0x14000100cc0}, 0x140005acbc0, 0x14000306ed0)
    	/Users/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GetRequiredPlugins_Handler({0x105c4c1c0?, 0x140000aebe0}, {0x105cd49e8, 0x140001b49f0}, 0x140001ed100, 0x140005ac5e0)
    	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.123.1-0.20240711160144-b8226b705890/proto/go/language_grpc.pb.go:313 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140001e8e00, {0x105cd49e8, 0x140001b4960}, {0x105ce0440, 0x140002ee180}, 0x14000031c20, 0x140005b70e0, 0x1064eed00, 0x0)
    	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xba0
    google.golang.org/grpc.(*Server).handleStream(0x140001e8e00, {0x105ce0440, 0x140002ee180}, 0x14000031c20)
    	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xc80
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 71
    	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x150

error: failed to discover plugin requirements: error reading from server: EOF
```

But manually inserting all the same resources into `Pulumi.yaml` works as expected.

### Example

The problem is reproducible whenever the program has references which don't resolve.

```
❯ cat resources.yaml
resources:
  whoamiDeployment:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        namespace: ${namespace}
        name: whoami
        labels:
          app: whoami
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: whoami
        template:
          metadata:
            labels:
              app: whoami
          spec:
            containers:
              - name: whoami
                image: ${image}
                ports:
                  - name: http
                    containerPort: 80
```

This will panic:
```
name: debug-merged-yaml
runtime:
  name: yaml
  options:
    compiler: "cat resources.yaml"
```

This will fail as expected:
```
❯ cat Pulumi.yaml
name: debug-merged-yaml
runtime:
  name: yaml
resources:
  whoamiDeployment:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        namespace: ${namespace}
        name: whoami
        labels:
          app: whoami
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: whoami
        template:
          metadata:
            labels:
              app: whoami
          spec:
            containers:
              - name: whoami
                image: ${image}
                ports:
                  - name: http
                    containerPort: 80
```

```
Previewing update (dev):
     Type                 Name                   Plan       Info
 +   pulumi:pulumi:Stack  debug-merged-yaml-dev  create     1 error

Diagnostics:
  pulumi:pulumi:Stack (debug-merged-yaml-dev):
    error: an unhandled error occurred: 1 error occurred:
    	* Pulumi.yaml:12,20-32: resource, variable, or config value "namespace" not found;
```

### Output of `pulumi about`

CLI
Version      3.128.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME  VERSION
language  yaml  unknown

Host
OS       darwin
Version  14.6
Arch     arm64

This project is written in yaml

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
