### ISSUE TITLE
Better error message when using Outputs as `import` argument

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-yaml#614]
A program that uses the resource [import option](https://www.pulumi.com/docs/concepts/options/import/) with an `Output` as the import id:

```yaml
config:
  azure-native:location: westus2
  rgId:
    type: string
resources:
  resourceGroup:
    type: azure-native:resources:ResourceGroup
    options:
      import: "${rgId}"
```

currently fails like this: `error: failed to discover plugin requirements: Pulumi.yaml:15,15-22: import must be a string.` This error message is somewhat misleading, although correct in a narrow sense (outputs are not strings).

It would be good to be clear to the user that Outputs are not supported here.

#608 attempted this but the approach wasn't correct.
