### ISSUE TITLE
Value of a resource's id output is empty

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-yaml#63]
A simple repro program:

```yaml
name: azure-test
runtime: yaml
resources:
  rg:
    type: azure-native:resources:ResourceGroup
outputs:
  test: ${rg.id}
```

When deployed, no output is returned as the `id` property is evaluated as nil.

`pulumi stack export` does return a valid `id`.
