### ISSUE TITLE
Interpolation doesn't handle list pathing correctly

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#65]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to get the following to compile (pass eval):
```
resources:
    bucket:
        type: aws:s3:Bucket
        properties:
            loggings:
                - targetBucket: ${logs.bucket}
    logs:
        type: aws:s3:Bucket
outputs:
    targetBucket: ${bucket.loggings[0].targetBucket}
```

To facilitate this, I provide the following mock:
```
func (m *testMonitor) NewResource(args pulumi.MockResourceArgs) (string, resource.PropertyMap, error) {
	switch args.Name {
	case "bucket":
		return args.Name, resource.NewPropertyMapFromMap(map[string]interface{}{
			"loggings": []interface{}{
				map[string]string{
					"targetBucket": "foo",
				},
			},
		}), nil
    // other stuff
}
```
This fails to evaluate, giving
```
--- FAIL: TestGenerateProgram (1.74s)
    --- FAIL: TestGenerateProgram/AWS_S3_with_logging (0.31s)
        gen_program_test.go:54: 
            	Error Trace:	gen_program_test.go:54
            	            				program_driver.go:269
            	Error:      	Received unexpected error:
            	            	waiting for RPCs: cannot access a list element using a property name
            	Test:       	TestGenerateProgram/AWS_S3_with_logging
FAIL
```

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:
