### ISSUE TITLE
Non-existing property is silently ignored

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-yaml#69]
I made a mistake while defining the following resource

```yaml
  kubeEnv:
    type: azure-native:web/v20210301:KubeEnvironment
    properties:
      resourceGroupName: ${resourceGroup.name}
      type: Managed
      appLogsConfiguration:
        destination: "log-analytics"
        logAnalyticsConfiguration:
          customerId: ${workspace.customerId}
          sharedKey: ${sharedKey}
```

The mistake is that the `type` property does not exist in the schema and it should be `environmentType`.

The YAML plugin and the engine both accepted my inputs and it got to a request to Azure API, which failed with a somewhat confusing error suggesting that I should set environment type to "Managed".

Expected result: Pulumi would catch my error at preview time and report that the `type` property doesn't exist.

I realize that the YAML plugin would need to fetch provider schema's to do so, so there probably is no short-term easy fix.

Side question - should the provider's Check catch this and complain about non-existing properties?
