### ISSUE TITLE
Having invalid `options:version` value on explicit provider causes conversion to produce incorrect output

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-yaml#702]
### What happened?

When attempting to use `pulumi convert` to generate additional examples from yaml to other languages, the other languages were missing the explicit provider.

### Example

<details>
<summary>Source YAML</summary>

```yaml
name: base
runtime: yaml

plugins:
  providers:
    - name: base
      path: ../../bin
resources:
  provider:
    type: pulumi:providers:base
    properties:
      accessToken: "accessToken123"
    options:
      version: 0.0.0-alpha.0 #Appending a "v" to the front of this actually makes it behave correctly
      pluginDownloadURL: https://testfakedownload
  my-account:
    type: base:Account
    properties:
      name: myaccount
    options:
      provider: ${provider}

outputs:
  myoutput: 
    fn::secret: ${my-account.secretValue}
```
</details>

### Command used
`pulumi convert --cwd ./examples/simple --language typescript --out ../test --logtostderr --generate-only --non-interactive`

<details><summary>Generated Typescript</summary>

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as base from "@pulumi/base";

const provider = new base.Provider("provider", {accessToken: "accessToken123"});
const myAccount = new base.Account("my-account", {name: "myaccount"});
export const myoutput = pulumi.secret(myAccount.secretValue);
```
</details>

### Output of `pulumi about`

```
CLI          
Version      3.143.0
yaml         converter  1.12.0 
```

### Additional context

I actually think this maybe should fail some sort of validation rather than succeeding incorrectly. In my testing, removing `version` or appending `v` to the front of the string actually makes it behave as expected. For example `version: v0.0.0-alpha.0`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
