### ISSUE TITLE
Assets properties of resources are not exported

### ISSUE THREAD

**Issue by julienp** [pulumi/pulumi-yaml#714]
In the following YAML program `file` is empty, but `fileVar` is correctly exported.

```yaml
name: yaml-bucket
runtime: yaml
variables:
  fileVar:
    fn::fileAsset: ./file.txt
resources:
  bucket:
    type: aws:s3:BucketV2
  textFile:
    type: aws:s3:BucketObjectv2
    properties:
      bucket: ${bucket.id}
      source:
        fn::fileAsset: ./file.txt
      key: file.txt
outputs:
  bucket: ${bucket.id}
  file: ${textFile.source}
  fileVar: ${fileVar}
```
Output:
```
Outputs:
    bucket : output<string>
    fileVar: asset(file:1c5b885) { ./file.txt }
```

In Python `file` is properly exported:

```python
import pulumi
from pulumi_aws import s3

bucket = s3.BucketV2("my-bucket")
file = s3.BucketObjectv2(
    "file.txt", bucket=bucket.id, source=pulumi.FileAsset("./file.txt")
)

pulumi.export("bucket", bucket.id)
pulumi.export("file", file.source)
pulumi.export("fileVar", pulumi.FileAsset("./file.txt"))
```
Output:
```
Outputs:
    bucket : output<string>
    file   : {
        path: "./file.txt"
    }
    fileVar: {
        path: "./file.txt"
    }
````
