### ISSUE TITLE
Add a built-in variable "pulumi" to expose an API similar to other language SDKs.

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#76]
To unblock resources requiring absolute paths (https://github.com/pulumi/pulumi-yaml/issues/4#issuecomment-1044441978) and to support a similar API surface as in our other SDKs, we will define a top level, reserved variable "pulumi".

This variable will have a definition equivalent to:

```yaml
variables:
  pulumi:
    cwd: # working directory of project
    stack: # equivalent to "pulumi.getStack()" in other languages
    project: # likewise with "pulumi.getProject()"
```

These variables can then be accessed via interpolation as any other output, config, or variable, e.g.:

```yaml
resources:
  myImage:
    type: docker:index/registryImage:RegistryImage
    properties:
      name: ${registry.loginServer}/node-app:v1.0.0
      build:
        context: ${pulumi.cwd}/node-app
```

"cwd" will follow the convention that "Pulumi.yaml" may define a different working directory, and the top level `${pulumi.cwd}` will follow that convention, see: https://www.pulumi.com/docs/intro/concepts/project/#paths
