### ISSUE TITLE
Allow object as resource property

### ISSUE THREAD

**Issue by dmfigol-aws** [pulumi/pulumi-yaml#770]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I use a cross-language component resource that accepts arguments like this:
```yaml
name: "pulumi-yaml"
cidrs:
  ipv4:
    - cidr: 10.20.0.0/16
    - cidr: 100.64.0.0/26
  ipv6:
    - {}
    - {size: 56}
tags:
  vpcTagKey: vpcTagValue
commonTags:
  commonTagKey: commonTagValue
extraOptions:
  enableDnsHostnames: false
  enableDnsSupport: false
```
I want to be able to use these values in the stack configuration:
```yaml
# Pulumi.dev.yaml
config:
  aws:region: eu-central-1
  aws-native:region: eu-central-1
  vpcArgs:
    name: "pulumi-yaml"
    cidrs:
      ipv4:
        - cidr: 10.20.0.0/16
        - cidr: 100.64.0.0/26
      ipv6:
        - {}
        - {size: 56}
    tags:
      vpcTagKey: vpcTagValue
    commonTags:
      commonTagKey: commonTagValue
    extraOptions:
      enableDnsHostnames: false
      enableDnsSupport: false
```
Unfortunately, the following reference in the project configuration doesn't work:
```yaml
# Pulumi.yaml
name: pulumi-aws-vpc-stacks
description: Pulumi VPC stacks deployed with YAML
runtime: yaml
plugins:
  providers:
    - name: aws-networking
      path: ../pulumi-aws-vpc
resources:
  vpc:
    type: aws-networking:index:VPC
    properties: ${vpcArgs}
outputs:
  vpcId: ${vpc.vpcId}
```
I receive the following error
```
-> % pulumi up
Previewing update (dev)
View in Browser (Ctrl+O): https://app.pulumi.com/<my-org>/pulumi-aws-vpc-stacks/dev/previews/1ad934b1-058f-406c-96aa-21e3dbcc0682
error: failed to discover package requirements: Pulumi.yaml:13,17-27: properties must be an object;
```
This enhancement request is to make such invocation possible.

### Workaround
Reference each key separately, but this is not very scalable
```yaml
# Pulumi.yaml
resources:
  vpc:
    type: aws-networking:index:VPC
    properties:
        name: ${vpcArgs.name}
        cidrs: ${vpcArgs.cidrs}
        tags: ${vpcArgs.tags}
        commonTags: ${vpcArgs.commonTags}
        extraOptions: ${vpcArgs.extraOptions}
```
