### ISSUE TITLE
Support `${resourceName}` in resource options that take resources as values

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#78]
The following resource options declared in the snippet below take resource references (CustomResourceState or ProviderResourceState properties), but in YAML take string parameters.

```yaml
resources:
  awsProvider: ...
  resourceFoo: ...
  resourceBar: ...
  resourceQuux:
    options:
      # strings, not resource references/expressions
      dependsOn: [resourceFoo, resourceBar]
      parent: resourceFoo
      provider: awsProvider
      # Not currently supported, relevant for multi-language components:
      # providers: [awsProvider, azureProvider, ...]
```

We know we want to unify our syntax for referring to resources as objects:
- #73 

So an open question to be resolved is whether we should support `${awsProvider}` or `${resourceFoo}` in these properties. This will require ensuring the values are prompt (see: #14) and/or allowing these properties to be Outputs throughout our ecosystem of MLCs and provider resources.
