### ISSUE TITLE
`replaceOnChanges` schema property not used

### ISSUE THREAD

**Issue by corymhall** [pulumi/pulumi-yaml#813]
### What happened?

The `aws-native` provider uses the `replaceOnChanges` schema property to indicate to the engine which properties should cause a replacement if changed. This doesn't appear to work for yaml programs.

### Example

For example given this update:

```yaml
name: test-aws-native
runtime: yaml
resources:
  vpc:
    type: aws-native:ec2:Vpc
    properties:
      cidrBlock: 10.21.0.0/16
```

to 

```yaml
name: test-aws-native
runtime: yaml
resources:
  vpc:
    type: aws-native:ec2:Vpc
    properties:
      cidrBlock: 10.20.0.0/16
```

We should get a replacement, but we do not.

`replaceOnChanges` is set in the schema for `cidrBlock` https://github.com/pulumi/pulumi-aws-native/blob/9fe06a916be30b8ceffcada82d457f0b4e540022/provider/cmd/pulumi-resource-aws-native/schema.json#L233115-L233119

In the nodejs sdk for example, the `replaceOnChanges` resource option is written in the SDK. https://github.com/pulumi/pulumi-aws-native/blob/568215a3a93acaa6eb72feb05b8cea2dd4121928/sdk/nodejs/ec2/vpc.ts#L135-L138

### Output of `pulumi about`

CLI          
Version      3.175.0
Go Version   go1.24.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws-native  unknown
language  yaml        1.19.2

Host     
OS       darwin
Version  15.5
Arch     arm64

This project is written in yaml

Current Stack: chall-pulumi-corp/test-aws-bucket-migration/chall

TYPE                         URN
pulumi:pulumi:Stack          urn:pulumi:chall::test-aws-bucket-migration::pulumi:pulumi:Stack::test-aws-bucket-migration-chall
pulumi:providers:aws-native  urn:pulumi:chall::test-aws-bucket-migration::pulumi:providers:aws-native::default
aws-native:ec2:Vpc           urn:pulumi:chall::test-aws-bucket-migration::aws-native:ec2:Vpc::vpc

Found no pending operations associated with chall

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/chall-pulumi-corp
User           chall-pulumi-corp
Organizations  chall-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME        VERSION
aws-native  

Pulumi locates its logs in /var/folders/3b/6mr1jkqx7r797ff75k27jfjc0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
