### ISSUE TITLE
Panic with Cloudflare program

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-yaml#814]
### What happened?

Got a panic trying to reproduce a cloudflare provider issue:

```
   provider_program_test.go:82: failed to preview update: failed to run preview: exit status 255
        code: 255
        stdout: Previewing update (test):
          pulumi:pulumi:Stack: (same)
            [urn=urn:pulumi:test::example-ruleset::pulumi:pulumi:Stack::example-ruleset-test]
        panic: interface conversion: ast.Expr is *ast.SymbolExpr, not *ast.StringExpr
        
        goroutine 63 [running]:
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*typeCache).typeExpr(0x1400003b350, 0x1400078c440, {0x105e26180?, 0x14000893a40})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1050 +0xf74
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.walk({0x1400045ab80, 0x1400045ab70, 0x1400045aba0, 0x1400045ab50, 0x1400045ab90, 0x1400045ab60}, 0x1400078c440, {0x105e26180, 0x14000893a40})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1278 +0x2c0
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.walk({0x1400045ab80, 0x1400045ab70, 0x1400045aba0, 0x1400045ab50, 0x1400045ab90, 0x1400045ab60}, 0x1400078c440, {0x105e26298, 0x14000893a70})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1254 +0x36c
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.walk({0x1400045ab80, 0x1400045ab70, 0x1400045aba0, 0x1400045ab50, 0x1400045ab90, 0x1400045ab60}, 0x1400078c440, {0x105e26180, 0x14000893aa0})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1263 +0x424
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.walk({0x1400045ab80, 0x1400045ab70, 0x1400045aba0, 0x1400045ab50, 0x1400045ab90, 0x1400045ab60}, 0x1400078c440, {0x105e26180, 0x14000893b60})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1263 +0x424
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.walk({0x1400045ab80, 0x1400045ab70, 0x1400045aba0, 0x1400045ab50, 0x1400045ab90, 0x1400045ab60}, 0x1400078c440, {0x105e26298, 0x14000893b90})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1254 +0x36c
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.walkPropertyMap({0x1400045ab80, 0x1400045ab70, 0x1400045aba0, 0x1400045ab50, 0x1400045ab90, 0x1400045ab60}, 0x1400078c440, {{{0x0, 0x0}}, {0x1400042a500, ...}})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1388 +0xec
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.EvalResource({0x1400045ab80, 0x1400045ab70, 0x1400045aba0, 0x1400045ab50, 0x1400045ab90, 0x1400045ab60}, 0x1400038b200, {{{0x105e21b00, 0x1400073be80}, 0x1400073af40, ...}, ...})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1352 +0x1bc
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*Runner).Run(0x1400038b200, {0x105e31e80, 0x1400003b440})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:1157 +0x37c
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.TypeCheck(0x1400038b200)
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:1225 +0x1d4
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.PrepareTemplate(0x1400038b200?, 0x140005a0d50?, {0x105e246c0?, 0x14000796a80?})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:469 +0x150
        
        github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.RunTemplate(0x1400059ec60, 0x140001ee000, 0x140004df570, {0x105e246c0, 0x14000796a80})
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:487 +0x148
        
        github.com/pulumi/pulumi-yaml/pkg/server.(*yamlLanguageHost).Run.func1(0x1400059ec60?)
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/server/server.go:319 +0x30
        
        github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0x1400059ec60, 0x140004df5a0)
        
        	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.173.0/go/pulumi/run.go:122 +0x16c
        
        github.com/pulumi/pulumi-yaml/pkg/server.(*yamlLanguageHost).Run(0x1400032e450, {0x105e2d5d8, 0x14000113ad0}, 0x1400014e400)
        
        	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/server/server.go:317 +0xf84
        
        github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_Run_Handler.func1({0x105e2d5d8?, 0x14000113ad0?}, {0x105dc28e0?, 0x1400014e400?})
        
        	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.173.0/proto/go/language_grpc.pb.go:484 +0xd0
        
        github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x105e2d5d8, 0x14000112e10}, {0x105dc28e0, 0x1400014e400}, 0x140005ab080, 0x14000315cc8)
        
        	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2d4
        
        github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_Run_Handler({0x105da46c0, 0x1400032e450}, {0x105e2d5d8, 0x14000112e10}, 0x14000307300, 0x140007961c0)
        
        	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.173.0/proto/go/language_grpc.pb.go:486 +0x148
        
        google.golang.org/grpc.(*Server).processUnaryRPC(0x1400025e200, {0x105e2d5d8, 0x14000112d80}, {0x105e3b460, 0x14000362820}, 0x140004297a0, 0x1400032e4e0, 0x1067ea6c8, 0x0)
        
        	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1394 +0xb64
        
        google.golang.org/grpc.(*Server).handleStream(0x1400025e200, {0x105e3b460, 0x14000362820}, 0x140004297a0)
        
        	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1805 +0xb20
        
        google.golang.org/grpc.(*Server).serveStreams.func2.1()
        
        	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1029 +0x84
        
        created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 61
        
        	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1040 +0x13c
        
        Resources:
            1 unchanged
        
        stderr: error: error reading from server: EOF
```

### Example

```yaml
name: example-ruleset
runtime: yaml

config:
  cloudflare-zone-id:
    type: string

resources:
  pagerule:
    type: cloudflare:PageRule
    properties:
      zoneId: ${cloudflare-zone-id}
      target: example.com
      priority: 1
      actions:
        - type: cache_level
          value: cache_level_bypass
          waf: "on"
  domain-rate-limit:
    type: cloudflare:Ruleset
    properties:
      name: domain-rate-lmit
      kind: zone
      zoneId: ${cloudflare-zone-id}
      phase: http_request_transform
      rules:
        - enabled: true
          description: "Execute Cloudflare Managed Ruleset"
          action: "execute"
          expression: "true"
          actionParameters:
            id: "4814384a9e5d4991b9815dcfc25d2f1f"
        - enabled: true
          description: "Execute Cloudflare Managed Ruleset 1"
          action: "execute"
          expression: "true"
          actionParameters:
            id: "4814384a9e5d4991b9815dcfc25d2f1d"
        - action: rewrite
          actionParameters:
            rules:
              - ${pagerule.id}: "4814384a9e5d4991b9815dcfc25d2f1f,4814384a9e5d4991b9815dcfc25d2f1d"
          enabled: true
          expression: "true"

```

config from `providers/cloudflare` ESC env

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.175.0
Go Version   go1.24.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  cloudflare  unknown
language  yaml        1.19.2

Host     
OS       darwin
Version  15.5
Arch     arm64

This project is written in yaml
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
