### ISSUE TITLE
Support using explicit providers with parameterization

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-yaml#824]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to use parameterized providers from YAML and use explicit providers with them, but it is not clear which type token should be used with the provider resource. Naively using something like `pulumi:providers:vpcmod` where `vpcmod` has an entry under packages is not working as expected:

```yaml
name: testproj-yaml
description: testproj-yaml
runtime: yaml
resources:
  testProvider:
    type: pulumi:providers:vpcmod
    properties:
      aws:
        region: us-west-2
  testVpc:
    type: vpcmod:index:Module
    options:
      provider: ${testProvider}
    properties:
      name: test-vpc-${pulumi.stack}
      azs:
        - us-west-2a
        - us-west-2b
        - us-west-2c
      cidr: 10.0.0.0/16
      public_subnets:
        - 10.0.1.0/24
        - 10.0.2.0/24
        - 10.0.3.0/24
      private_subnets:
        - 10.0.5.0/24
        - 10.0.6.0/24
        - 10.0.7.0/24
      database_subnets:
        - 10.0.9.0/24
        - 10.0.10.0/24
        - 10.0.11.0/24
      create_database_subnet_group: true
  testRdsSg:
    type: aws:ec2:SecurityGroup
    properties:
      vpcId: ${testVpc.vpc_id}
  testRdsSgIngress:
    type: aws:vpc:SecurityGroupIngressRule
    properties:
      ipProtocol: tcp
      securityGroupId: ${testRdsSg.id}
      cidrIpv4: ${testVpc.vpc_cidr_block}
      fromPort: 3306
      toPort: 3306
  testRds:
    type: rdsmod:index:Module
    properties:
      engine: mysql
      identifier: test-rds-${pulumi.stack}
      manage_master_user_password: true
      publicly_accessible: false
      allocated_storage: 20
      max_allocated_storage: 100
      instance_class: db.t4g.large
      engine_version: 8
      family: mysql8.0
      db_name: completeMysql
      username: complete_mysql
      port: '3306'
      multi_az: true
      db_subnet_group_name: ${testVpc.database_subnet_group_name}
      vpc_security_group_ids:
        - ${testRdsSg.id}
      skip_final_snapshot: true
      deletion_protection: false
      create_db_option_group: false
      create_db_parameter_group: false
packages:
  rdsmod:
    source: terraform-module
    version: 0.1.7
    parameters:
      - terraform-aws-modules/rds/aws
      - 6.10.0
      - rdsmod
  vpcmod:
    source: terraform-module
    version: 0.1.7
    parameters:
      - terraform-aws-modules/vpc/aws
      - 5.19.0
      - vpcmod
```

This attempts to download the provider instead of recognizing the parameterization:

```
Previewing update (dev1)

View in Browser (Ctrl+O): https://app.pulumi.com/anton-pulumi-corp/testproj-yaml/dev1/previews/f13aa171-f823-4336-85e5-45b8f6bfc67f

     Type                        Name                Plan       Info
 +   pulumi:pulumi:Stack         testproj-yaml-dev1  create     2 messages
     └─ pulumi:providers:vpcmod  testProvider                   1 error

Diagnostics:
  pulumi:pulumi:Stack (testproj-yaml-dev1):
    Using Terraform CLI for schema inference
    Using Terraform CLI for schema inference

  pulumi:providers:vpcmod (testProvider):
    error: Could not automatically download and install resource plugin 'pulumi-resource-vpcmod' at version v0.1.7, install the plugin using `pulumi plugin install resource vpcmod v0.1.7`: error downloading provider vpcmod to file: failed to download plugin: vpcmod-0.1.7: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-vpcmod-v0.1.7-darwin-arm64.tar.gz

Resources:
    + 1 to create
```

Ideally the canonical way to do this could be documented here:

https://www.pulumi.com/docs/iac/languages-sdks/yaml/yaml-language-reference/#explicit-provider
