### ISSUE TITLE
Normalize config in DAG sort

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#88]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Right now, we sort all dependencies except for config dependencies. This means that config values can rely on each other (via `Default`) as long as they are in sorted order. To rectify this corner case (and fix a programgen example) we should add config to the normal sorting. This also allows setting default values to output properties or the results of invokes. For example:
```yaml
# Taken from the `azure-sa` programgen example. 
configuration:
    locationParam:
        type: string
        default: ${resourceGroupVar}
variables:
    resourceGroupVar:
        Fn::Invoke:
            Function: azure:core/getResourceGroup:getResourceGroup
            Arguments:
                name: ${resourceGroupNameParam}
            Return: location
```
### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:
